// <auto-generated />
namespace ClothKai.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addNewPropertiesToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewPropertiesToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105110749316_addNewPropertiesToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
