// <auto-generated />
namespace ClothKai.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageURLProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageURLProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202104230634113_imageURLProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
